language: node_js
node_js:
  - "8.11"
services:
  - docker
script:
  - npm run lint
  - npm run test -- --coverage
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
deploy:
asdasdhjnkadjn
