dist: trusty
sudo: required
language: node_js
node_js:
  - "8.11"
services:
  - docker
script:
  - npm run lint
  - npm run test -- --coverage
deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/docker-push.sh
    on:
      tags: true
